# Generated by Django 4.2.3 on 2023-07-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_account_activate_useraccountactivationkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_activate',
            field=models.BooleanField(default=False),
        ),
    ]
